### ISSUE TITLE
I constantly get the error message "No SD Card attached"

### ISSUE THREAD

**Issue by guilhae** [Winston-Lu/ESP32-Cam-Timelapse#1]
This is what i get in the console:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
Startup
Going to sleep for 0 secondsets Jun  8 2016 00:22:57

rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
Startup
No SD Card attached

**Comment by Winston-Lu** [comment]
This may be because either the SD card is bad or if the SD card is formatted with a format the ESP32 can't read (It should be FAT/FAT32, it wont wont work if the SD card is formatted with exFAT, NTFS, etc.). Check with your computer what the SD card is formatted with change it if needed.

The SD card reader library is unable to detect what type of SD card it is. Try to avoid partitioning the drive past the supported 4GB max size supported by the library, as larger partitions may not work. In my case, I was able to use a 16gb Kingston micro SD cards with no issues, but SD cards vary from manufacturer to manufacturer

**Comment by Gammler84** [comment]
I had the same problem with all of my microSD cards (old with <4GB and new >4GB). My solution was to change the line 132 and 133.

if(!SD_MMC.begin()){Serial.println("SD Card Mount Failed");return;}
uint8_t cardType = SD_MMC.cardType();

So the microSD Card will first initialized and only then the type is queried. Maybe there is some changes in the "SD_MMC.h" library that the type can only read out after initialization

**Comment by Winston-Lu** [comment]
Hm, that seems reasonable. I updated the repo with this change c9dc955
